version: '2'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=passwordatabase
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=bitnami_myapp
    ports:
      - 3306:3306
    networks:
      - mynetwork1

  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
      - '5173:5173'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=bitnami_myapp
      - DB_PASSWORD=passwordatabase
    volumes:
      - './my-app:/app'
    depends_on:
      - mysql
    networks:
      - mynetwork1

  pma:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8083:80
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=passwordatabase
    depends_on:
      - mysql
    networks:
      - mynetwork1

networks:
  mynetwork1:
